services:
  navidrome:
    image: deluan/navidrome:latest

    container_name: navidrome

    user: "1000:1000"

    restart: unless-stopped

    ports:
      - "4533:4533"

    mem_limit: 256m

    networks:
      - proxy

    environment:
      TZ: Asia/Ho_Chi_Minh

      ND_MUSICFOLDER: /music
      ND_DATAFOLDER: /data

      ND_LOGLEVEL: info

      # Disable scheduled scans
      ND_SCANSCHEDULE: "0"

      # Disable Prometheus metrics
      ND_PROMETHEUS_ENABLED: "false"

      # Keep users logged in
      ND_SESSIONTIMEOUT: 24h

    volumes:
      # Metadata database
      - navidrome_data:/data

      # Music library
      - /mnt/nas_storage/huyquach/music:/music:ro

networks:
  proxy:
    external: true

volumes:
  navidrome_data: